defmodule Dispatch.Repo.Migrations.IdentityAndAccess do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:contacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :organization_id, :uuid, null: false
      add :kind, :text, null: false
      add :name, :text, null: false
      add :phone_e164, :text
      add :email, :citext
      add :status, :text, null: false, default: "ACTIVE"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create table(:devices, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :participant_id, :uuid, null: false
      add :installation_id, :text, null: false
    end

    create unique_index(:devices, [:installation_id], name: "devices_unique_installation_index")

    alter table(:devices) do
      add :public_key, :text, null: false
      add :last_sequence, :bigint, null: false, default: 0
      add :status, :text, null: false, default: "ACTIVE"
      add :last_seen_at, :utc_datetime_usec

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create table(:organization_memberships, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :organization_id, :uuid, null: false
      add :user_id, :uuid, null: false
      add :status, :text, null: false, default: "ACTIVE"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create table(:organizations, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:contacts) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "contacts_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:contacts, [:tenant_id, :phone_e164],
             name: "contacts_unique_active_phone_index",
             where: "(status = 'ACTIVE' AND phone_e164 IS NOT NULL)"
           )

    alter table(:organization_memberships) do
      modify :organization_id,
             references(:organizations,
               column: :id,
               name: "organization_memberships_organization_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:organizations) do
      add :name, :text, null: false
      add :kind, :text, null: false
      add :status, :text, null: false, default: "ACTIVE"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:participants, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:devices) do
      modify :participant_id,
             references(:participants,
               column: :id,
               name: "devices_participant_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:participants) do
      add :tenant_id, :uuid, null: false
      add :user_id, :uuid, null: false

      add :home_organization_id,
          references(:organizations,
            column: :id,
            name: "participants_home_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :public_name, :text, null: false
      add :status, :text, null: false, default: "ACTIVE"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create table(:role_assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :principal_type, :text, null: false
      add :principal_id, :uuid, null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "role_assignments_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :role_definition_id, :uuid, null: false
      add :scope_type, :text, null: false
      add :scope_id, :uuid
      add :starts_at, :utc_datetime_usec, null: false
      add :ends_at, :utc_datetime_usec
      add :status, :text, null: false, default: "ACTIVE"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create table(:role_definitions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:role_assignments) do
      modify :role_definition_id,
             references(:role_definitions,
               column: :id,
               name: "role_assignments_role_definition_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(
             :role_assignments,
             [
               :tenant_id,
               :principal_type,
               :principal_id,
               :organization_id,
               :role_definition_id,
               :scope_type,
               :scope_id
             ],
             name: "role_assignments_unique_active_grant_index",
             nulls_distinct: false,
             where: "(status = 'ACTIVE')"
           )

    alter table(:role_definitions) do
      add :tenant_id, :uuid, null: false
      add :key, :text, null: false
      add :label, :text, null: false
      add :capability_schema_version, :bigint, null: false, default: 1
      add :capabilities_json, {:array, :text}, null: false, default: []
      add :constraints_json, :map, null: false, default: %{}
      add :profile_module, :text, null: false
      add :status, :text, null: false, default: "ACTIVE"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create unique_index(:role_definitions, [:tenant_id, :key],
             name: "role_definitions_unique_tenant_key_index"
           )

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:organization_memberships) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "organization_memberships_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:organization_memberships, [:tenant_id, :organization_id, :user_id],
             name: "organization_memberships_unique_active_membership_index",
             where: "(status = 'ACTIVE')"
           )

    alter table(:participants) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "participants_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:participants, [:tenant_id, :user_id, :home_organization_id],
             name: "participants_unique_user_home_organization_index",
             where: "(status = 'ACTIVE')"
           )

    alter table(:users) do
      add :oidc_subject, :text, null: false
      add :display_name, :text, null: false
      add :email, :citext
      add :status, :text, null: false, default: "ACTIVE"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:oidc_subject], name: "users_unique_oidc_subject_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:oidc_subject], name: "users_unique_oidc_subject_index")

    alter table(:users) do
      remove :updated_at
      remove :created_at
      remove :status
      remove :email
      remove :display_name
      remove :oidc_subject
    end

    drop constraint(:participants, "participants_home_organization_id_fkey")

    drop constraint(:participants, "participants_user_id_fkey")

    drop_if_exists unique_index(:participants, [:tenant_id, :user_id, :home_organization_id],
                     name: "participants_unique_user_home_organization_index"
                   )

    alter table(:participants) do
      modify :user_id, :uuid
    end

    drop constraint(:organization_memberships, "organization_memberships_user_id_fkey")

    drop constraint(:organization_memberships, "organization_memberships_organization_id_fkey")

    drop_if_exists unique_index(
                     :organization_memberships,
                     [:tenant_id, :organization_id, :user_id],
                     name: "organization_memberships_unique_active_membership_index"
                   )

    alter table(:organization_memberships) do
      modify :user_id, :uuid
    end

    drop table(:users)

    drop_if_exists unique_index(:role_definitions, [:tenant_id, :key],
                     name: "role_definitions_unique_tenant_key_index"
                   )

    alter table(:role_definitions) do
      remove :version
      remove :updated_at
      remove :created_at
      remove :status
      remove :profile_module
      remove :constraints_json
      remove :capabilities_json
      remove :capability_schema_version
      remove :label
      remove :key
      remove :tenant_id
    end

    drop constraint(:role_assignments, "role_assignments_role_definition_id_fkey")

    drop constraint(:role_assignments, "role_assignments_organization_id_fkey")

    drop_if_exists unique_index(
                     :role_assignments,
                     [
                       :tenant_id,
                       :principal_type,
                       :principal_id,
                       :organization_id,
                       :role_definition_id,
                       :scope_type,
                       :scope_id
                     ], name: "role_assignments_unique_active_grant_index")

    alter table(:role_assignments) do
      modify :role_definition_id, :uuid
    end

    drop table(:role_definitions)

    drop table(:role_assignments)

    alter table(:participants) do
      remove :version
      remove :updated_at
      remove :created_at
      remove :status
      remove :public_name
      remove :home_organization_id
      remove :user_id
      remove :tenant_id
    end

    drop constraint(:devices, "devices_participant_id_fkey")

    alter table(:devices) do
      modify :participant_id, :uuid
    end

    drop table(:participants)

    alter table(:organizations) do
      remove :updated_at
      remove :created_at
      remove :status
      remove :kind
      remove :name
    end

    alter table(:organization_memberships) do
      modify :organization_id, :uuid
    end

    drop constraint(:contacts, "contacts_organization_id_fkey")

    drop_if_exists unique_index(:contacts, [:tenant_id, :phone_e164],
                     name: "contacts_unique_active_phone_index"
                   )

    alter table(:contacts) do
      modify :organization_id, :uuid
    end

    drop table(:organizations)

    drop table(:organization_memberships)

    alter table(:devices) do
      remove :version
      remove :updated_at
      remove :created_at
      remove :last_seen_at
      remove :status
      remove :last_sequence
      remove :public_key
    end

    drop_if_exists unique_index(:devices, [:installation_id],
                     name: "devices_unique_installation_index"
                   )

    drop table(:devices)

    drop table(:contacts)
  end
end
