defmodule Dispatch.Repo.Migrations.StatusEventsAndAudit do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:audit_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :event_type, :text, null: false
      add :actor_type, :text, null: false
      add :actor_id, :uuid
      add :role_assignment_id, :uuid
      add :subject_type, :text, null: false
      add :subject_id, :uuid
      add :occurred_at, :utc_datetime_usec, null: false
      add :correlation_id, :text
      add :payload_json, :map, null: false, default: %{}
      add :previous_event_hash, :text
      add :event_hash, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:audit_events, [:event_hash],
             name: "audit_events_unique_event_hash_index"
           )

    create table(:participant_status_events, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :participant_id, :uuid, null: false
      add :role_assignment_id, :uuid, null: false
      add :assignment_id, :uuid
      add :status, :text, null: false
      add :occurred_at, :utc_datetime_usec, null: false
      add :recorded_at, :utc_datetime_usec, null: false
      add :source, :text, null: false, default: "PARTICIPANT"
      add :note, :text
      add :location_sample_id, :uuid
      add :verification, :text, null: false, default: "NONE"
      add :supersedes_event_id, :uuid
      add :device_id, :uuid
      add :device_sequence, :bigint
      add :correlation_id, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:participant_status_events, [:device_id, :device_sequence],
             name: "participant_status_events_unique_device_sequence_index",
             where: "(device_id IS NOT NULL AND device_sequence IS NOT NULL)"
           )
  end

  def down do
    drop_if_exists unique_index(:participant_status_events, [:device_id, :device_sequence],
                     name: "participant_status_events_unique_device_sequence_index"
                   )

    drop table(:participant_status_events)

    drop_if_exists unique_index(:audit_events, [:event_hash],
                     name: "audit_events_unique_event_hash_index"
                   )

    drop table(:audit_events)
  end
end
