defmodule Dispatch.Repo.Migrations.LoadsStopsAndParties do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:assignment_contacts, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :assignment_id, :uuid, null: false

      add :contact_id,
          references(:contacts,
            column: :id,
            name: "assignment_contacts_contact_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :relationship, :text, null: false
    end

    create unique_index(
             :assignment_contacts,
             [:tenant_id, :assignment_id, :contact_id, :relationship],
             name: "assignment_contacts_unique_contact_relationship_index"
           )

    alter table(:assignment_contacts) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:assignments, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:assignment_contacts) do
      modify :assignment_id,
             references(:assignments,
               column: :id,
               name: "assignment_contacts_assignment_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:assignments) do
      add :tenant_id, :uuid, null: false
      add :load_id, :uuid, null: false
      add :operator_participant_id, :uuid, null: false
      add :vehicle_id, :uuid
      add :trailer_id, :uuid
      add :starts_at, :utc_datetime_usec, null: false
      add :ends_at, :utc_datetime_usec
      add :operator_exclusive, :boolean, null: false, default: true
      add :status, :text, null: false, default: "PLANNED"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create table(:load_parties, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :load_id, :uuid, null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "load_parties_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :relationship, :text, null: false
      add :starts_at, :utc_datetime_usec, null: false
      add :ends_at, :utc_datetime_usec
      add :status, :text, null: false, default: "ACTIVE"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create table(:loads, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:assignments) do
      modify :load_id,
             references(:loads,
               column: :id,
               name: "assignments_load_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:assignments, [:tenant_id, :operator_participant_id],
             name: "assignments_one_active_per_operator_index",
             where: "(status = 'ACTIVE' AND operator_exclusive)"
           )

    alter table(:load_parties) do
      modify :load_id,
             references(:loads,
               column: :id,
               name: "load_parties_load_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:load_parties, [:tenant_id, :load_id, :organization_id, :relationship],
             name: "load_parties_unique_active_relationship_index",
             where: "(status = 'ACTIVE')"
           )

    alter table(:loads) do
      add :tenant_id, :uuid, null: false
      add :carrier_organization_id, :uuid, null: false
      add :broker_organization_id, :uuid
      add :external_reference, :text
      add :commodity_text, :text
      add :status, :text, null: false, default: "DRAFT"
      add :currency, :text
      add :agreed_rate_minor, :bigint

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create unique_index(:loads, [:tenant_id, :broker_organization_id, :external_reference],
             name: "loads_unique_external_reference_index",
             where: "(external_reference IS NOT NULL AND broker_organization_id IS NOT NULL)"
           )

    create table(:stop_parties, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :stop_id, :uuid, null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "stop_parties_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :relationship, :text, null: false
      add :starts_at, :utc_datetime_usec, null: false
      add :ends_at, :utc_datetime_usec
      add :status, :text, null: false, default: "ACTIVE"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create table(:stops, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
    end

    alter table(:stop_parties) do
      modify :stop_id,
             references(:stops,
               column: :id,
               name: "stop_parties_stop_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:stop_parties, [:tenant_id, :stop_id, :organization_id, :relationship],
             name: "stop_parties_unique_active_relationship_index",
             where: "(status = 'ACTIVE')"
           )

    alter table(:stops) do
      add :tenant_id, :uuid, null: false

      add :load_id,
          references(:loads,
            column: :id,
            name: "stops_load_id_fkey",
            type: :uuid,
            prefix: "public"
          ), null: false

      add :sequence, :bigint, null: false
    end

    create unique_index(:stops, [:tenant_id, :load_id, :sequence],
             name: "stops_unique_sequence_per_load_index"
           )

    alter table(:stops) do
      add :kind, :text, null: false
      add :address_text, :text, null: false
      add :position, :"geography(Point,4326)"
      add :window_start, :utc_datetime_usec
      add :window_end, :utc_datetime_usec
      add :contact_name, :text
      add :contact_phone_e164, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create table(:trailers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :organization_id, :uuid, null: false
      add :unit_number, :text, null: false
      add :plate, :text
      add :status, :text, null: false, default: "ACTIVE"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create unique_index(:trailers, [:tenant_id, :organization_id, :unit_number],
             name: "trailers_unique_unit_number_index"
           )

    create table(:vehicles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :tenant_id, :uuid, null: false
      add :organization_id, :uuid, null: false
      add :unit_number, :text, null: false
      add :plate, :text
      add :status, :text, null: false, default: "ACTIVE"

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :version, :bigint, null: false, default: 0
    end

    create unique_index(:vehicles, [:tenant_id, :organization_id, :unit_number],
             name: "vehicles_unique_unit_number_index"
           )
  end

  def down do
    drop_if_exists unique_index(:vehicles, [:tenant_id, :organization_id, :unit_number],
                     name: "vehicles_unique_unit_number_index"
                   )

    drop table(:vehicles)

    drop_if_exists unique_index(:trailers, [:tenant_id, :organization_id, :unit_number],
                     name: "trailers_unique_unit_number_index"
                   )

    drop table(:trailers)

    drop constraint(:stops, "stops_load_id_fkey")

    alter table(:stops) do
      remove :version
      remove :updated_at
      remove :created_at
      remove :contact_phone_e164
      remove :contact_name
      remove :window_end
      remove :window_start
      remove :position
      remove :address_text
      remove :kind
    end

    drop_if_exists unique_index(:stops, [:tenant_id, :load_id, :sequence],
                     name: "stops_unique_sequence_per_load_index"
                   )

    alter table(:stops) do
      remove :sequence
      remove :load_id
      remove :tenant_id
    end

    drop constraint(:stop_parties, "stop_parties_organization_id_fkey")

    drop constraint(:stop_parties, "stop_parties_stop_id_fkey")

    drop_if_exists unique_index(
                     :stop_parties,
                     [:tenant_id, :stop_id, :organization_id, :relationship],
                     name: "stop_parties_unique_active_relationship_index"
                   )

    alter table(:stop_parties) do
      modify :stop_id, :uuid
    end

    drop table(:stops)

    drop table(:stop_parties)

    drop_if_exists unique_index(
                     :loads,
                     [:tenant_id, :broker_organization_id, :external_reference],
                     name: "loads_unique_external_reference_index"
                   )

    alter table(:loads) do
      remove :version
      remove :updated_at
      remove :created_at
      remove :agreed_rate_minor
      remove :currency
      remove :status
      remove :commodity_text
      remove :external_reference
      remove :broker_organization_id
      remove :carrier_organization_id
      remove :tenant_id
    end

    drop constraint(:load_parties, "load_parties_organization_id_fkey")

    drop constraint(:load_parties, "load_parties_load_id_fkey")

    drop_if_exists unique_index(
                     :load_parties,
                     [:tenant_id, :load_id, :organization_id, :relationship],
                     name: "load_parties_unique_active_relationship_index"
                   )

    alter table(:load_parties) do
      modify :load_id, :uuid
    end

    drop constraint(:assignments, "assignments_load_id_fkey")

    drop_if_exists unique_index(:assignments, [:tenant_id, :operator_participant_id],
                     name: "assignments_one_active_per_operator_index"
                   )

    alter table(:assignments) do
      modify :load_id, :uuid
    end

    drop table(:loads)

    drop table(:load_parties)

    alter table(:assignments) do
      remove :version
      remove :updated_at
      remove :created_at
      remove :status
      remove :operator_exclusive
      remove :ends_at
      remove :starts_at
      remove :trailer_id
      remove :vehicle_id
      remove :operator_participant_id
      remove :load_id
      remove :tenant_id
    end

    drop constraint(:assignment_contacts, "assignment_contacts_contact_id_fkey")

    drop constraint(:assignment_contacts, "assignment_contacts_assignment_id_fkey")

    alter table(:assignment_contacts) do
      modify :assignment_id, :uuid
    end

    drop table(:assignments)

    alter table(:assignment_contacts) do
      remove :updated_at
      remove :created_at
    end

    drop_if_exists unique_index(
                     :assignment_contacts,
                     [:tenant_id, :assignment_id, :contact_id, :relationship],
                     name: "assignment_contacts_unique_contact_relationship_index"
                   )

    drop table(:assignment_contacts)
  end
end
